version: '3.6'

services:
  maintainer:
      container_name: "maintainer"
      build:
        context: ./docker/maintainer/
        dockerfile: Dockerfile
      ports:
        - 8090:8080
      volumes:
        - db_logs:/usr/local/tomcat/db_volume/db_logs
        - db_config:/usr/local/tomcat/db_volume/db_config
        - db_content:/usr/local/tomcat/db_volume/db_content
        - app_logs:/usr/local/tomcat/app_volume/app_logs
        - app_config:/usr/local/tomcat/app_volume/app_config
        - app_content:/usr/local/tomcat/app_volume/app_content
        - ./docker/volumes/maintainer/webapps:/usr/local/tomcat/webapps
        - ./docker/volumes/maintainer/app_backup:/usr/local/tomcat/app_backup
        - ./docker/volumes/maintainer/db_backup:/usr/local/tomcat/db_backup
      depends_on:
        - application
        - database

  application:
    container_name: "application"
    build:
      context: ./docker/application/
      dockerfile: Dockerfile
#    image: tomcat:latest
    environment:
      JDBC_URL: jdbc:mysql://database:3306/dailydockerdb?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: admin
      JDBC_PASS: admin
    ports:
      - 8080:8080
    volumes:
      - app_logs:/usr/local/tomcat/logs
      - app_config:/usr/local/tomcat/conf
      - app_content:/usr/local/tomcat/content
      - ./docker/volumes/application/scores:/usr/local/tomcat/scores
      - ./docker/volumes/application/webapps:/usr/local/tomcat/webapps
    links:
      - database

  database:
    container_name: "database"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: dailydockerdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - db_logs:/var/log/mysql
      - db_config:/etc/mysql
      - db_content:/var/lib/mysql
      - ./docker/volumes/database/script:/docker-entrypoint-initdb.d

volumes:
  app_logs:
  app_config:
  app_content:
  db_logs:
  db_config:
  db_content: