FROM mysql:latest
#RUN apt-get update
#RUN apt-get -y install cron
#RUN apt-get -y install rsync grsync
#RUN mkdir cron
#RUN mkdir logs_backup
#RUN mkdir config_backup
#RUN mkdir database_backup
#COPY cron/db_backup /cron
#COPY cron/db_backup.sh /cron
#RUN crontab /cron/db_backup
#RUN chmod 0644 /cron/db_backup
#RUN service cron restart