FROM tomcat:latest
#RUN apt-get update
#RUN apt-get -y install cron
#RUN apt-get -y install rsync grsync
#RUN mkdir /usr/local/tomcat/cron
#RUN mkdir /usr/local/tomcat/scores
#RUN mkdir /usr/local/tomcat/logs_backup
#RUN mkdir /usr/local/tomcat/config_backup
#COPY cron/app_backup /usr/local/tomcat/cron
#COPY cron/app_backup.sh /usr/local/tomcat/cron
#RUN crontab /usr/local/tomcat/cron/app_backup
#RUN chmod 0644 /usr/local/tomcat/cron/app_backup
#RUN service cron restart